### ISSUE TITLE
Error when adding GoogleCalendarSkill config

### ISSUE THREAD

**Issue by ghost** [jcasoft/GoogleCalendarSkill#1]
2017-01-28 07:04:55,537 - mycroft.configuration - ERROR - Error loading configuration '/home/saroj/mycroft-core/mycroft/configuration/mycroft.conf'
2017-01-28 07:04:55,537 - mycroft.configuration - ERROR - ValueError('No JSON object could be decoded',)
2017-01-28 07:04:55,537 - mycroft.configuration - DEBUG - Configuration '/etc/mycroft/mycroft.conf' not found
2017-01-28 07:04:55,538 - mycroft.configuration - ERROR - Error loading configuration '/home/saroj/.mycroft/mycroft.conf'
2017-01-28 07:04:55,538 - mycroft.configuration - ERROR - ValueError('Extra data: line 1 column 19 - line 9 column 1 (char 18 - 150)',)
2017-01-28 07:04:55,538 - mycroft.configuration - ERROR - Invalid configuration: {}
Traceback (most recent call last):
  File "/home/saroj/mycroft-core/mycroft/skills/main.py", line 23, in <module>
    from mycroft.messagebus.client.ws import WebsocketClient
  File "/home/saroj/mycroft-core/mycroft/messagebus/client/ws.py", line 34, in <module>
    config = ConfigurationManager.get().get("websocket")
  File "/home/saroj/mycroft-core/mycroft/configuration/__init__.py", line 179, in get
    ConfigurationManager.load_defaults()
  File "/home/saroj/mycroft-core/mycroft/configuration/__init__.py", line 158, in load_defaults
    return RemoteConfiguration.load(ConfigurationManager.__config)
  File "/home/saroj/mycroft-core/mycroft/configuration/__init__.py", line 107, in load
    RemoteConfiguration.validate(config)
  File "/home/saroj/mycroft-core/mycroft/configuration/__init__.py", line 103, in validate
    raise TypeError
TypeError

**Comment by jcasoft** [comment]
GoogleCalendarSkill is available to be installed by MSM and with manual method for Mark1
